travis:
  secure:
    BINSTAR_TOKEN: taF2j3CvGARSSHcx0e5rtsFqHZOd2Nlv4mx7h7Gecd2Esi7DP//VJCdGp3EzS7HdC1x38p3PkmoPZkogdIGHxLpcB4ITejubHzEja7vp1mGzlNJTBSeIBAlmp4lhUzqN+d5GLKh1ers9vAYarGmjO/+7VOuYMlhl0tRq1zhyp4xt+5GkftFTlQ9j4ueD9YLsrTL4SaOXLrGl4q/62b0BYkr+FccbN2+w2H1Go2GTAjZQmYxh0qOsIH4i5Sptn/vmDTkp0jubIo/UJ9/VAbBIJ48CFoZp9cv+R2vAR/JWlL6sTxwZlCGKbv9y5WYTslTHZhHFuX2Mp0q64o0dUdi+mu5tnXKm1INK7fl0Up0vf+RSInYKBi1ErMoGeAzwX3X1BmuFbmwanNhVUECnEUgwiphdcID8TyfO9YyDZVceflUaO158ZI8JBEaGCRS0Y2nqWFf4NpEnLrOafz5GWD/hYgPAf9Tp/7UXYyEzkAHu9+ttRKfrnCio61Asj8MhPHHamBiJGDWvQnu2Q1+d/eprrFydrUUqbJ1Xveg+galvMJsoilXQd/p+C+T6V0qnkYigoSJNqLzgZvR5q0ncmFsrNWHBOoWO9TjlnnvBn7KiS/gnm820/jAsD33iixp5WYiv12J9gW6DZCg/y2VoWkIHVlD3Uk9itSCU/sMcE5hRJzQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
