travis:
  secure:
    BINSTAR_TOKEN: DMRTyR697LpGkaarDHgkCZepFYhfxPzMs3zcPcNw9U9r5np0cS5SY0+K+hJH52Ejlf3Q8A8GtRQiNSNshOeWI/IzAlgVCcf/gUCJS7FfjhaiId1hl2jd7v4yS1usDfnpGctJYhbRlCvFKnKpAX8X6vmRyKNgNLlH7GL1ieX+Regqlec0jNK4OLpFe+c7h8PWTcvBimW1qV0j3VQNust3Lf9WFJjQq0RYeyUg7mbBRHgN40PXGXSFraCwpmtaD52xQWd1rDQfLreq4JWB7NvnPHV8C4s6/uuM0shsVuVRDXFP0cTItVzKzlu7fud81yQZAJL2htdAu3BX8pU7C8SS93z+tcNjNBSGwdsqf8mKG/s5erLk0kss/TTXdOYv/J1GtQZPRHdY+svTVU5i9VtNpGk+ho1fWH6zJl9BRsbAMrP4/mcze8VT+P9++7vOCFa/Wbw9+SwziZsu3JOKVu99XAk8P4BZRt/Cj1VSieOj5GtzvGRoG4G1D++xdWVsyffBtvbI/qBN13GK+u6ztN3yDV1tkIo8vsAZWsim75vPWEc0TUsc1m//x5mfdP9UsUW9d9ruQDppf+RRKWpx1l1WuNnft04UYPldDOkX8H8c2Rr641Y7QlYRKjYoz90sxxyERtDQEEOWrKpq3fUIwkynsHMGXYrnt4QRizWStJIW0Qg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
